version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1 curl
            pip install --upgrade awscli
      - run:
          name: Install gcloud SDK and authenticate
          command: |
            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz
            tar -zxf google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz
            ./google-cloud-sdk/install.sh --disable-prompts
            echo ${GOOGLE_AUTH} > gcp-key.json
            ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file gcp-key.json
            ./google-cloud-sdk/bin/gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Build docker image
          command: |
            docker build -t sosimon/atpricetracker .
            docker tag sosimon/atpricetracker sosimon/atpricetracker:${CIRCLE_SHA1:0:8}
            docker tag sosimon/atpricetracker $GOOGLE_GCR_URL/atpricetracker:${CIRCLE_SHA1:0:8}
      - deploy:
          name: Push docker image to Docker hub, GCP GCR
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push sosimon/atpricetracker:${CIRCLE_SHA1:0:8}
            ./google-cloud-sdk/bin/gcloud docker -- push ${GOOGLE_GCR_URL}/atpricetracker:${CIRCLE_SHA1:0:8}
