version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add --no-cache py-pip=9.0.0-r1 curl
      - run:
          name: Install gcloud SDK and authenticate
          command: |
            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz
            tar -zxf google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-x86_64.tar.gz
            ./google-cloud-sdk/install.sh --quiet
            echo ${GOOGLE_AUTH} > gcp-key.json
            ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file gcp-key.json
            ./google-cloud-sdk/bin/gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Build docker image
          command: |
            docker build -t sosimon/atpricetracker .
      - run:
          name: Tag and push docker image to GCP GCR
          command: |
            IMAGE_TAG=$(cat VERSION.txt)
            docker tag sosimon/atpricetracker $GOOGLE_GCR_URL/atpricetracker:${IMAGE_TAG}
            ./google-cloud-sdk/bin/gcloud docker -- push ${GOOGLE_GCR_URL}/atpricetracker:${IMAGE_TAG}
  deploy:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - run:
          name: Install components and authenticate
          command: |
            gcloud --quiet components install kubectl beta
            echo ${GOOGLE_AUTH} > gcp-key.json
            gcloud auth activate-service-account --key-file gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set container/use_v1_api_client false
            gcloud beta container clusters get-credentials ${GOOGLE_CLUSTER_NAME} --region ${GOOGLE_REGION}
            kubectl version
      - run:
          name: Deploy 
          command: |
            kubectl get pods
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
